#pragma checksum "C:\Users\selma\source\repos\EdutronPortal\EdutronPortal\Views\Home\List.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "c9b83885e8141038e660f74132fd9a3ab94729b9"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Home_List), @"mvc.1.0.view", @"/Views/Home/List.cshtml")]
[assembly:global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/Views/Home/List.cshtml", typeof(AspNetCore.Views_Home_List))]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"c9b83885e8141038e660f74132fd9a3ab94729b9", @"/Views/Home/List.cshtml")]
    public class Views_Home_List : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<IEnumerable<EdutronPortal.Models.EgitimTanim>>
    {
        #line hidden
        #pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
        #pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.HeadTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_HeadTagHelper;
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.BodyTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_BodyTagHelper;
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#line 2 "C:\Users\selma\source\repos\EdutronPortal\EdutronPortal\Views\Home\List.cshtml"
  
    Layout = null;

#line default
#line hidden
            BeginContext(81, 29, true);
            WriteLiteral("\r\n<!DOCTYPE html>\r\n\r\n<html>\r\n");
            EndContext();
            BeginContext(110, 99, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("head", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "bfcb53e4a97d42e482287b4bf6a020cd", async() => {
                BeginContext(116, 86, true);
                WriteLiteral("\r\n    <meta name=\"viewport\" content=\"width=device-width\" />\r\n    <title>List</title>\r\n");
                EndContext();
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_HeadTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.HeadTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_HeadTagHelper);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(209, 2, true);
            WriteLiteral("\r\n");
            EndContext();
            BeginContext(211, 675, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("body", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "a602c78d59bd4099b2bddcb315163c58", async() => {
                BeginContext(217, 298, true);
                WriteLiteral(@"
    <table>
        <thead>
            <tr>
                <th>Kategori</th>
                <th>Eğitmen Bilgileri</th>
                <th>Kontenjan Sayisi</th>
                <th>Maliyet</th>
                <th>Süre Bilgisi</th>
            </tr>
        </thead>
       <tbody>
");
                EndContext();
#line 25 "C:\Users\selma\source\repos\EdutronPortal\EdutronPortal\Views\Home\List.cshtml"
            foreach (var egitim in Model)
           {

#line default
#line hidden
                BeginContext(572, 36, true);
                WriteLiteral("           <tr>\r\n               <td>");
                EndContext();
                BeginContext(609, 15, false);
#line 28 "C:\Users\selma\source\repos\EdutronPortal\EdutronPortal\Views\Home\List.cshtml"
              Write(egitim.Kategori);

#line default
#line hidden
                EndContext();
                BeginContext(624, 26, true);
                WriteLiteral("</td>\r\n               <td>");
                EndContext();
                BeginContext(651, 21, false);
#line 29 "C:\Users\selma\source\repos\EdutronPortal\EdutronPortal\Views\Home\List.cshtml"
              Write(egitim.EgitmenBilgisi);

#line default
#line hidden
                EndContext();
                BeginContext(672, 26, true);
                WriteLiteral("</td>\r\n               <td>");
                EndContext();
                BeginContext(699, 22, false);
#line 30 "C:\Users\selma\source\repos\EdutronPortal\EdutronPortal\Views\Home\List.cshtml"
              Write(egitim.KontenjanSayisi);

#line default
#line hidden
                EndContext();
                BeginContext(721, 26, true);
                WriteLiteral("</td>\r\n               <td>");
                EndContext();
                BeginContext(748, 14, false);
#line 31 "C:\Users\selma\source\repos\EdutronPortal\EdutronPortal\Views\Home\List.cshtml"
              Write(egitim.Maliyet);

#line default
#line hidden
                EndContext();
                BeginContext(762, 26, true);
                WriteLiteral("</td>\r\n               <td>");
                EndContext();
                BeginContext(789, 20, false);
#line 32 "C:\Users\selma\source\repos\EdutronPortal\EdutronPortal\Views\Home\List.cshtml"
              Write(egitim.SureBilgileri);

#line default
#line hidden
                EndContext();
                BeginContext(809, 25, true);
                WriteLiteral("</td>\r\n           </tr>\r\n");
                EndContext();
#line 34 "C:\Users\selma\source\repos\EdutronPortal\EdutronPortal\Views\Home\List.cshtml"
           }

#line default
#line hidden
                BeginContext(848, 31, true);
                WriteLiteral("       </tbody>\r\n    </table>\r\n");
                EndContext();
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_BodyTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.BodyTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_BodyTagHelper);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(886, 11, true);
            WriteLiteral("\r\n</html>\r\n");
            EndContext();
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<IEnumerable<EdutronPortal.Models.EgitimTanim>> Html { get; private set; }
    }
}
#pragma warning restore 1591
