#pragma checksum "C:\Users\selma\source\repos\EdutronPortal\EdutronPortal\Views\Home\MyView.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "ae477e3e15d51344b596ef3ea5bfd62282db1e54"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Home_MyView), @"mvc.1.0.view", @"/Views/Home/MyView.cshtml")]
[assembly:global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/Views/Home/MyView.cshtml", typeof(AspNetCore.Views_Home_MyView))]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"ae477e3e15d51344b596ef3ea5bfd62282db1e54", @"/Views/Home/MyView.cshtml")]
    public class Views_Home_MyView : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    {
        #line hidden
        #pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
        #pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.HeadTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_HeadTagHelper;
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.BodyTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_BodyTagHelper;
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            BeginContext(1, 5, false);
#line 1 "C:\Users\selma\source\repos\EdutronPortal\EdutronPortal\Views\Home\MyView.cshtml"
Write(Model);

#line default
#line hidden
            EndContext();
            BeginContext(6, 35, true);
            WriteLiteral(" EdutronPortal.Models.EgitimTanim\r\n");
            EndContext();
#line 2 "C:\Users\selma\source\repos\EdutronPortal\EdutronPortal\Views\Home\MyView.cshtml"
  
    Layout = null;

#line default
#line hidden
            BeginContext(68, 29, true);
            WriteLiteral("\r\n<!DOCTYPE html>\r\n\r\n<html>\r\n");
            EndContext();
            BeginContext(97, 211, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("head", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "ef1152996ad34138a8d857527d6437c7", async() => {
                BeginContext(103, 198, true);
                WriteLiteral("\r\n    <meta name=\"viewport\" content=\"width=device-width\" />\r\n    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\" />\r\n    <title>MyView</title>\r\n");
                EndContext();
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_HeadTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.HeadTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_HeadTagHelper);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(308, 2, true);
            WriteLiteral("\r\n");
            EndContext();
            BeginContext(310, 667, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("body", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "5da9f2884171489c99e44862659516c3", async() => {
                BeginContext(316, 45, true);
                WriteLiteral("\r\n    <div class=\"text-center\">\r\n        <h2>");
                EndContext();
                BeginContext(362, 14, false);
#line 16 "C:\Users\selma\source\repos\EdutronPortal\EdutronPortal\Views\Home\MyView.cshtml"
       Write(Model.Kategori);

#line default
#line hidden
                EndContext();
                BeginContext(376, 35, true);
                WriteLiteral("</h2>\r\n        <hr />\r\n        <h2>");
                EndContext();
                BeginContext(412, 20, false);
#line 18 "C:\Users\selma\source\repos\EdutronPortal\EdutronPortal\Views\Home\MyView.cshtml"
       Write(Model.EgitmenBilgisi);

#line default
#line hidden
                EndContext();
                BeginContext(432, 35, true);
                WriteLiteral("</h2>\r\n        <hr />\r\n        <h2>");
                EndContext();
                BeginContext(468, 13, false);
#line 20 "C:\Users\selma\source\repos\EdutronPortal\EdutronPortal\Views\Home\MyView.cshtml"
       Write(Model.Maliyet);

#line default
#line hidden
                EndContext();
                BeginContext(481, 35, true);
                WriteLiteral("</h2>\r\n        <hr />\r\n        <h2>");
                EndContext();
                BeginContext(517, 19, false);
#line 22 "C:\Users\selma\source\repos\EdutronPortal\EdutronPortal\Views\Home\MyView.cshtml"
       Write(Model.SureBilgileri);

#line default
#line hidden
                EndContext();
                BeginContext(536, 35, true);
                WriteLiteral("</h2>\r\n        <hr />\r\n        <h2>");
                EndContext();
                BeginContext(572, 21, false);
#line 24 "C:\Users\selma\source\repos\EdutronPortal\EdutronPortal\Views\Home\MyView.cshtml"
       Write(Model.KontenjanSayisi);

#line default
#line hidden
                EndContext();
                BeginContext(593, 23, true);
                WriteLiteral("</h2>\r\n        <hr />\r\n");
                EndContext();
                BeginContext(876, 94, true);
                WriteLiteral("\r\n        Tanımlanan Eğitimleri <a asp-action=\"List\" btn btn-primary>Listele</a>\r\n    </div>\r\n");
                EndContext();
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_BodyTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.BodyTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_BodyTagHelper);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(977, 11, true);
            WriteLiteral("\r\n</html>\r\n");
            EndContext();
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; }
    }
}
#pragma warning restore 1591
